// <auto-generated />
using System;
using AAPS.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AAPS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AAPS.Api.Models.Adocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdotanteId")
                        .HasColumnType("int");

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAdocao")
                        .HasColumnType("date");

                    b.Property<int>("PontoAdocaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdotanteId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("PontoAdocaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Adocao", "dbo");
                });

            modelBuilder.Entity("AAPS.Api.Models.Adotante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Cep")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LocalTrabalho")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("SituacaoEndereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Adotante", "dbo");
                });

            modelBuilder.Entity("AAPS.Api.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int>("DoadorId")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pelagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DoadorId");

                    b.ToTable("Animal", "dbo");
                });

            modelBuilder.Entity("AAPS.Api.Models.AnimalEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAcompanhamento")
                        .HasColumnType("date");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("EventoId");

                    b.ToTable("AnimalEvento", "dbo");
                });

            modelBuilder.Entity("AAPS.Api.Models.Doador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Cep")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("Doador", "dbo");
                });

            modelBuilder.Entity("AAPS.Api.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Code")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Evento", "dbo");
                });

            modelBuilder.Entity("AAPS.Api.Models.PontoAdocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Cep")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.ToTable("PontoAdocao", "dbo");
                });

            modelBuilder.Entity("AAPS.Api.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdotanteId")
                        .HasColumnType("int");

                    b.Property<int>("DoadorId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("PontoAdocaoId")
                        .HasColumnType("int");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("AdotanteId");

                    b.HasIndex("DoadorId");

                    b.HasIndex("PontoAdocaoId");

                    b.ToTable("Telefone", "dbo");
                });

            modelBuilder.Entity("AAPS.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.Property<byte>("Nivel")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Usuario", "dbo");
                });

            modelBuilder.Entity("AAPS.Api.Models.Adocao", b =>
                {
                    b.HasOne("AAPS.Api.Models.Adotante", "Adotante")
                        .WithMany("Adocoes")
                        .HasForeignKey("AdotanteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AAPS.Api.Models.Animal", "Animal")
                        .WithMany("Adocoes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AAPS.Api.Models.PontoAdocao", "PontoAdocao")
                        .WithMany("Adocoes")
                        .HasForeignKey("PontoAdocaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AAPS.Api.Models.Usuario", "Usuario")
                        .WithMany("Adocoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Adotante");

                    b.Navigation("Animal");

                    b.Navigation("PontoAdocao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AAPS.Api.Models.Animal", b =>
                {
                    b.HasOne("AAPS.Api.Models.Doador", "Doador")
                        .WithMany("Animais")
                        .HasForeignKey("DoadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doador");
                });

            modelBuilder.Entity("AAPS.Api.Models.AnimalEvento", b =>
                {
                    b.HasOne("AAPS.Api.Models.Animal", "Animal")
                        .WithMany("AnimalEventos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AAPS.Api.Models.Evento", "Evento")
                        .WithMany("AnimalEventos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AAPS.Api.Models.Telefone", b =>
                {
                    b.HasOne("AAPS.Api.Models.Adotante", "Adotante")
                        .WithMany("Telefones")
                        .HasForeignKey("AdotanteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AAPS.Api.Models.Doador", "Doador")
                        .WithMany("Telefones")
                        .HasForeignKey("DoadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AAPS.Api.Models.PontoAdocao", "PontoAdocao")
                        .WithMany("Telefones")
                        .HasForeignKey("PontoAdocaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Adotante");

                    b.Navigation("Doador");

                    b.Navigation("PontoAdocao");
                });

            modelBuilder.Entity("AAPS.Api.Models.Adotante", b =>
                {
                    b.Navigation("Adocoes");

                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("AAPS.Api.Models.Animal", b =>
                {
                    b.Navigation("Adocoes");

                    b.Navigation("AnimalEventos");
                });

            modelBuilder.Entity("AAPS.Api.Models.Doador", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("AAPS.Api.Models.Evento", b =>
                {
                    b.Navigation("AnimalEventos");
                });

            modelBuilder.Entity("AAPS.Api.Models.PontoAdocao", b =>
                {
                    b.Navigation("Adocoes");

                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("AAPS.Api.Models.Usuario", b =>
                {
                    b.Navigation("Adocoes");
                });
#pragma warning restore 612, 618
        }
    }
}
